/*
*******************************************************************
Content in this file is taken from http://www.uesp.net/wiki/Lore:Dragon_Language
The content is licensed under the Creative Commons by-sa license.
http://creativecommons.org/licenses/by-sa/2.5/
*/

var dict = {
	"aan": "a",
	"ahrk": "and",
	"ahst": "at",
	"ao": "wrath",
	"bah": "lightning",
	"bahlok": "hunger",
	"dah": "push",
	"dein": "keep",
	"diivon": "swallow",
	"do": "of",
	"dova": "dragon",
	"dovahkiin": "dragonborn",
	"draal": "pray",
	"fah": "for",
	"feyn": "bane",
	"fin": "the",
	"fod": "when",
	"fundein": "unfurled",
	"fus": "force",
	"graan": "rout",
	"hin": "your",
	"hon": "hear",
	"jun": "kings",
	"kein": "war",
	"kiin": "child",
	"kel": "scrolls",
	"klo": "sand",
	"ko": "in",
	"kogaan": "blessing",
	"krah": "cold",
	"krein": "sun",
	"kruziik": "ancient",
	"lein": "world",
	"los": "is",
	"lost": "have",
	"mahfaeraak": "forever",
	"meyz": "come",
	"mu": "we",
	"naal": "by",
	"norok": "fiercest",
	"nus": "statue",
	"nust": "they",
	"ok": "his",
	"paal": "foes",
	"prodah": "foretold",
	"ro": "balance",
	"roh": "balance",
	"staadnau": "unbound",
	"strun": "storm",
	"tiid": "time",
	"tol": "that",
	"toor": "inferno",
	"thuum": "voice",
	"ul": "eternity",
	"vaal": "bay",
	"vahriin": "sworn",
	"ved": "black",
	"viing": "wings",
	"vokul": "evil",
	"vokun": "shadow",
	"voth": "with",
	"wah": "to",
	"win": "wage",
	"yol": "fire",
	"zaan": "shout",
	"zeymah": "brothers",
	"zin": "honor",
	"zindro": "triumph"
};
